rabbitmq:
  container_name: "MessageQueueServer"
  image: rabbitmq:3-management
  ports:
    - "9002:15672"
    - "5672:5672"
api:
  build: api/.
  container_name: "ApiServer"
  links:
    - rabbitmq
  ports:
    - "8080:8080"
  worker:
  build: worker/.
  container_name: "Worker"
  links:
    - rabbitmq
    - elasticsearch
elasticsearch:
  container_name: "ElasticsearchServer"
  image: elasticsearch:latest
  ports:
    - "19200:9200"
    - "19300:9300"
